let express = require('express')
let router = express.Router()
let user = require('./api/user')
let login = require('./api/login')
let add = require('./api/add')
let dele = require('./api/dele')
let edit = require('./api/edit')
router.get('/loginInfo', user.get)
router.post('/login', login.post)
router.post('/add', add.post)
router.post('/dele', dele.post)
router.post('/edit', edit.post)
module.exports = router
