let express = require('express')
let router = express.Router()
let user = require('./api/user')
let login = require('./api/login')
let add = require('./api/add')
let dele = require('./api/dele')
let edit = require('./api/edit')
let goodsInfo=require('./api/goodsInfo')
let brandCategory=require('./api/brandCategory')
let addGoods=require('./api/addGoods')
let deleGoods=require('./api/deleGoods')
router.get('/loginInfo', user.get)
router.post('/login', login.post)
router.post('/add', add.post)
router.post('/dele', dele.post)
router.post('/edit', edit.post)
router.post('/addGoods', addGoods.post)
router.post('/deleGoods', deleGoods.post)
router.get('/goodsInfo',goodsInfo.get)
router.get('/brandCategory',brandCategory.get)
module.exports = router
